name: GSheet Occasion Reminder

on:
  schedule:
    # Every day at 01:05 UTC ≈ 06:35 IST
    - cron:  '5 1 * * *'
  workflow_dispatch:

jobs:
  reminder:
    runs-on: ubuntu-latest
    env:
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Restore credential files and token.pickle from GitHub secrets
      - name: Write credentials
        shell: bash
        env:
          GMAIL_CREDS_JSON:  ${{ secrets.GMAIL_CREDS_JSON }}
          SHEET_CREDS_JSON:  ${{ secrets.SHEET_CREDS_JSON }}
          GMAIL_TOKEN_P64:   ${{ secrets.GMAIL_TOKEN_P64 }}
        run: |
          echo "$GMAIL_CREDS_JSON"  > credentials.json
          echo "$SHEET_CREDS_JSON"  > credentials_sheet.json
          echo "$GMAIL_TOKEN_P64"   | base64 -d > token.pickle

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth google-auth-oauthlib google-api-python-client pandas

      - name: Run main.py
        run: python main.py
